if "[ $(tput colors) = 16777216 ]" {
  set -g default-terminal "tmux-direct"
} {
  if "[ $(tput colors) = 256 ]" {
    set -g default-terminal "tmux-256color"
  } {
    set -g default-terminal "tmux"
  }
}

unbind c-b

bind c-space send-prefix
bind r source-file ~/.config/tmux/tmux.conf
bind \% split-window -h -c "#{pane_current_path}"
bind \" split-window -v -c "#{pane_current_path}"
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel

set -g prefix c-space
set -s escape-time 10
set -g display-panes-time 1250
set -g mode-keys vi
set -g status-keys vi
set -g renumber-windows on
set -g allow-rename on
set -s set-clipboard on
set -g base-index 1
set -g pane-base-index 1
